
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eunace Faith Emactao
 */
public class SKIBIDIS extends javax.swing.JFrame {
    private void loadLoans() {
    try {
        Connection conn = LOANSHARK.getConnection();

        String sql = "SELECT * FROM list WHERE userId = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Session.userId);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) TABLE.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID"),
                rs.getString("FullName"),
                rs.getString("address"),
                rs.getString("contactNumber"),
                rs.getDouble("amountOfLoan"),
                rs.getString("years"),
                rs.getString("months"),
                rs.getDouble("interestRate"),
                rs.getDouble("monthlyPayment"),
                rs.getDouble("amountPaid"),
                rs.getDouble("totalPayment")
            });
        }

        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    
    
    
    
    
    
    
    
    
Connection conn = LOANSHARK.getConnection();
    /**
     * Creates new form SKIBIDIS
     */
    public SKIBIDIS() {
        initComponents();
        loadLoans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FULLNAME = new javax.swing.JTextField();
        ADDRESS = new javax.swing.JTextField();
        CONTACT = new javax.swing.JTextField();
        AMOUNTOFLOAN = new javax.swing.JTextField();
        YEARS = new javax.swing.JTextField();
        MONTHS = new javax.swing.JTextField();
        INTERESTRATE = new javax.swing.JTextField();
        MONTHLYPAYMENT = new javax.swing.JTextField();
        TOTALPAYMENT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        CALCULATE = new javax.swing.JButton();
        ADDLOAN = new javax.swing.JButton();
        SHOW = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PAY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(144, 190, 109));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("LOAN SHARK ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smiled-business-shark-holding-cash-260nw-62259715-removebg-preview (1).png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smiled-business-shark-holding-cash-260nw-62259715-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(505, 505, 505))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FULLNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FULLNAMEActionPerformed(evt);
            }
        });

        CONTACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTACTActionPerformed(evt);
            }
        });

        MONTHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONTHSActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FULL NAME :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ADDRESS :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONTACT # :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("AMOUNT :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("YEARS :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("INTEREST RATE :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MONTHS :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("MONTHLY PAYMENT:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TOTAL PAYMENT:");

        TABLE.setBackground(new java.awt.Color(255, 255, 255));
        TABLE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FULL NAME", "ADDRESS", "Contact #", "AMOUNT OF LOAN", "YEARS", "MONTHS", "INTEREST RATE", "MONTHLY PAYMENT", "AMOUNT PAID", "TOTAL PAYMENT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLE.setToolTipText("");
        jScrollPane1.setViewportView(TABLE);

        CALCULATE.setBackground(new java.awt.Color(144, 190, 109));
        CALCULATE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CALCULATE.setForeground(new java.awt.Color(0, 0, 0));
        CALCULATE.setText("CALCULATE LOAN");
        CALCULATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATEActionPerformed(evt);
            }
        });

        ADDLOAN.setBackground(new java.awt.Color(144, 190, 109));
        ADDLOAN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ADDLOAN.setForeground(new java.awt.Color(0, 0, 0));
        ADDLOAN.setText("ADD LOAN");
        ADDLOAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDLOANActionPerformed(evt);
            }
        });

        SHOW.setBackground(new java.awt.Color(144, 190, 109));
        SHOW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SHOW.setForeground(new java.awt.Color(0, 0, 0));
        SHOW.setText("SHOW");
        SHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWActionPerformed(evt);
            }
        });

        DELETE.setBackground(new java.awt.Color(144, 190, 109));
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DELETE.setForeground(new java.awt.Color(0, 0, 0));
        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(144, 190, 109));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("EXIT ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PAY.setBackground(new java.awt.Color(144, 190, 109));
        PAY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PAY.setForeground(new java.awt.Color(0, 0, 0));
        PAY.setText("PAY");
        PAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MONTHLYPAYMENT)
                            .addComponent(MONTHS)
                            .addComponent(YEARS)
                            .addComponent(AMOUNTOFLOAN)
                            .addComponent(CONTACT)
                            .addComponent(ADDRESS)
                            .addComponent(FULLNAME)
                            .addComponent(INTERESTRATE, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TOTALPAYMENT, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CALCULATE, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ADDLOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PAY, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AMOUNTOFLOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YEARS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MONTHS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INTERESTRATE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MONTHLYPAYMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TOTALPAYMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CALCULATE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADDLOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PAY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 793, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MONTHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONTHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONTHSActionPerformed

    private void CALCULATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATEActionPerformed

        try {

            String fullName = FULLNAME.getText().trim();
            String address = ADDRESS.getText().trim();

            StringBuilder missingFields = new StringBuilder();

            if (fullName.isEmpty()) {
                missingFields.append("Full Name\n");
            }
            if (address.isEmpty()) {
                missingFields.append("Address\n");
            }
            if (AMOUNTOFLOAN.getText().trim().isEmpty()) {
                missingFields.append("Loan Amount\n");
            }
            if (INTERESTRATE.getText().trim().isEmpty()) {
                missingFields.append("Interest Rate\n");
            }

            String yearsText = YEARS.getText().trim();
            String monthsText = MONTHS.getText().trim();

            if (yearsText.isEmpty() && monthsText.isEmpty()) {
                missingFields.append("Either Years or Months\n");
            }

            if (missingFields.length() > 0) {
                JOptionPane.showMessageDialog(this,
                    "Please fill in the following fields:\n" + missingFields.toString(),
                    "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double loanAmount = Double.parseDouble(AMOUNTOFLOAN.getText());
            double annualInterestRate = Double.parseDouble(INTERESTRATE.getText());

            int years = 0;
            int months = 0;

            if (!yearsText.isEmpty()) {
                years = Integer.parseInt(yearsText);
            }
            if (!monthsText.isEmpty()) {
                months = Integer.parseInt(monthsText);
            }

            int numberOfPayments = (years * 12) + months;

            if (numberOfPayments <= 0) {
                JOptionPane.showMessageDialog(this,
                    "Please enter a valid number of Years, Months, or both.",
                    "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double timeInYears = numberOfPayments / 12.0;

            double interest = loanAmount * (annualInterestRate / 100) * timeInYears;

            double totalPayment = loanAmount + interest;
            double monthlyPayment = totalPayment / numberOfPayments;

            MONTHLYPAYMENT.setText("" + String.format("%.2f", monthlyPayment));
            TOTALPAYMENT.setText("" + String.format("%.2f", totalPayment));

            System.out.println("Customer Full Name: " + fullName);
            System.out.println("Customer Address: " + address);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Please enter valid numbers in all numeric fields.",
                "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CALCULATEActionPerformed

    private void ADDLOANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDLOANActionPerformed
                                        
    try {
        Connection conn = LOANSHARK.getConnection();

        String fullName = FULLNAME.getText().trim();
        String contact = CONTACT.getText().trim();
        String address = ADDRESS.getText().trim();
        String amountOfLoan = AMOUNTOFLOAN.getText().trim();
        String years = YEARS.getText().trim();
        String months = MONTHS.getText().trim();
        String interestRate = INTERESTRATE.getText().trim();
        String monthlyPayment = MONTHLYPAYMENT.getText().trim();
        String totalPayment = TOTALPAYMENT.getText().trim();

        if (fullName.isEmpty() || contact.isEmpty() || address.isEmpty()
                || amountOfLoan.isEmpty() || interestRate.isEmpty()
                || monthlyPayment.isEmpty() || totalPayment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill all required fields!");
            return;
        }

        String sql = "INSERT INTO list (userId, FullName, address, contactNumber, amountOfLoan, years, months, interestRate, monthlyPayment, amountPaid, totalPayment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

PreparedStatement pst = conn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);

pst.setInt(1, Session.userId); // userId FIRST
pst.setString(2, fullName);
pst.setString(3, address);
pst.setString(4, contact);
pst.setDouble(5, Double.parseDouble(amountOfLoan));
pst.setString(6, years.isEmpty() ? null : years);
pst.setString(7, months.isEmpty() ? null : months);
pst.setDouble(8, Double.parseDouble(interestRate));
pst.setDouble(9, Double.parseDouble(monthlyPayment));
pst.setDouble(10, 0.0);
pst.setDouble(11, Double.parseDouble(totalPayment));
        pst.executeUpdate();

        ResultSet rs = pst.getGeneratedKeys();
        int id = 0;
        if (rs.next()) {
            id = rs.getInt(1);
        }

        DefaultTableModel model = (DefaultTableModel) TABLE.getModel();

        model.addRow(new Object[]{
            id,
            fullName,
            address,
            contact,
            amountOfLoan,
            years.isEmpty() ? "N/A" : years,
            months.isEmpty() ? "N/A" : months,
            interestRate,
            monthlyPayment,
            "0.00",
            totalPayment
        });

        JOptionPane.showMessageDialog(this, "Saved Successfully!");

        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_ADDLOANActionPerformed


    private void SHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWActionPerformed
                                     

    int row = TABLE.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a row!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) TABLE.getModel();

    String fullName = model.getValueAt(row, 1).toString();
    String address = model.getValueAt(row, 2).toString();
    String contact = model.getValueAt(row, 3).toString();
    String amount = model.getValueAt(row, 4).toString();
    String years = model.getValueAt(row, 5).toString();
    String months = model.getValueAt(row, 6).toString();
    String rate = model.getValueAt(row, 7).toString();
    String monthly = model.getValueAt(row, 8).toString();
    String paid = model.getValueAt(row, 9).toString();
    String total = model.getValueAt(row, 10).toString();

    double paidVal = Double.parseDouble(paid);
    double totalVal = Double.parseDouble(total);
    double remaining = totalVal - paidVal;

   JOptionPane.showMessageDialog(this,
        "ID: " + model.getValueAt(row, 0) +
        "\nName: " + fullName +
        "\nAddress: " + address +
        "\nContact: " + contact +
        "\nLoan Amount: " + amount +
        "\nYears: " + years +
        "\nMonths: " + months +
        "\nInterest Rate: " + rate +
        "\nMonthly Payment: " + monthly +
        "\nAmount Paid: " + paid +
        "\nTotal Payment: " + total +
        "\nRemaining: ₱" + remaining

    );

    }//GEN-LAST:event_SHOWActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
             int row = TABLE.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a row first!");
    return;
}


int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this record?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return; 
}

try {
    Connection conn = LOANSHARK.getConnection();
    DefaultTableModel model = (DefaultTableModel) TABLE.getModel();

    int id = Integer.parseInt(model.getValueAt(row, 0).toString());

    String sql = "DELETE FROM list WHERE ID = ?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setInt(1, id);

    pst.executeUpdate();

    model.removeRow(row);

    JOptionPane.showMessageDialog(this, "Deleted!");

    conn.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
                              
                                    

    }//GEN-LAST:event_DELETEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int result = JOptionPane.showConfirmDialog(this, // Reference to the current SKIBIDIS JFrame
                "Are you sure you want to log out?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (result == JOptionPane.YES_OPTION) {
            dispose();
            new Login().setVisible(true);
        }


    }                                        
    public static double Pmt(double r, double n, double p) {

        if (r == 0) {

            return -p / n;
        } else {

            return r * p / (1 - Math.pow(1 + r, -n));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAYActionPerformed
              int row = TABLE.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a loan first!");
        return;
    }

    try {
        DefaultTableModel model = (DefaultTableModel) TABLE.getModel();

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        double currentPaid = Double.parseDouble(model.getValueAt(row, 9).toString());
        double totalPayment = Double.parseDouble(model.getValueAt(row, 10).toString());

        String input = JOptionPane.showInputDialog(this, "Enter payment amount:");

        if (input == null || input.trim().isEmpty()) {
            return; 
        }

        double payAmount = Double.parseDouble(input);

        if (payAmount <= 0) {
            JOptionPane.showMessageDialog(this, "Invalid payment amount!");
            return;
        }

        double newPaid = currentPaid + payAmount;

        if (newPaid > totalPayment) {
            JOptionPane.showMessageDialog(this, "Payment exceeds total loan!");
            return;
        }

        double remaining = totalPayment - newPaid;

   
        Connection conn = LOANSHARK.getConnection();

        String sql = "UPDATE list SET amountPaid = ? WHERE ID = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setDouble(1, newPaid);
        pst.setInt(2, id);
        pst.executeUpdate();

        conn.close();

      
        model.setValueAt(String.format("%.2f", newPaid), row, 9);
        

        JOptionPane.showMessageDialog(this, "Payment updated successfully!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
                      
   
    }//GEN-LAST:event_PAYActionPerformed

    private void CONTACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONTACTActionPerformed

    private void FULLNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FULLNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FULLNAMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SKIBIDIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SKIBIDIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SKIBIDIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SKIBIDIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SKIBIDIS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDLOAN;
    private javax.swing.JTextField ADDRESS;
    private javax.swing.JTextField AMOUNTOFLOAN;
    private javax.swing.JButton CALCULATE;
    private javax.swing.JTextField CONTACT;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField FULLNAME;
    private javax.swing.JTextField INTERESTRATE;
    private javax.swing.JTextField MONTHLYPAYMENT;
    private javax.swing.JTextField MONTHS;
    private javax.swing.JButton PAY;
    private javax.swing.JButton SHOW;
    private javax.swing.JTable TABLE;
    private javax.swing.JTextField TOTALPAYMENT;
    private javax.swing.JTextField YEARS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
